#! /bin/bash

set -e

# Make sure this happens first, or the attempt to fire up the service
# will fail.
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  statsny.public
fi

#DEBHELPER#
